version: '3'

services:
  database:
    image: 'postgres:15.3-alpine3.18'
    container_name: "database"
    ports:
      - 2000:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: QWEqwe123
      POSTGRES_DATABASE: Practice
    volumes:
      - ./sqldata:/var/lib/postgresql/data
